# Generated by Django 3.1.3 on 2020-11-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('temp', models.FloatField()),
                ('ph', models.FloatField()),
                ('device_id', models.CharField(max_length=255)),
            ],
        ),
    ]
